# Form implementation generated from reading ui file '.\ui\group_radio.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 10, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 250, 250, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 40, 77, 74))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_py = QtWidgets.QRadioButton(self.widget)
        self.radioButton_py.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton_py)
        self.radioButton_java = QtWidgets.QRadioButton(self.widget)
        self.radioButton_java.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_java)
        self.radioButton_javascript = QtWidgets.QRadioButton(self.widget)
        self.radioButton_javascript.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_javascript)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(40, 160, 118, 74))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_debit = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_debit.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_debit)
        self.radioButton_paypal = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_paypal.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_paypal)
        self.radioButton_cash = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_cash.setObjectName("radioButton_6")
        self.verticalLayout_2.addWidget(self.radioButton_cash)

        self.radioButton_py.toggled.connect(self.radio_selected)
        self.radioButton_java.toggled.connect(self.radio_selected)
        self.radioButton_javascript.toggled.connect(self.radio_selected)
        self.radioButton_debit.toggled.connect(self.radio_selected)
        self.radioButton_paypal.toggled.connect(self.radio_selected)
        self.radioButton_cash.toggled.connect(self.radio_selected)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def radio_selected(self):
        selected1 = ""
        selected2 = ""

        if self.radioButton_py.isChecked():
            selected1 = "Python"
        elif self.radioButton_java.isChecked():
            selected1 = "Java"
        elif self.radioButton_javascript.isChecked():
            selected1 = "JS"

        if self.radioButton_debit.isChecked():
            selected2 = "Debit/Credit Card"
        if self.radioButton_paypal.isChecked():
            selected2 = "Paypal"
        if self.radioButton_cash.isChecked():
            selected2 = "Cash"

        self.label_3.setText("You choose {} and {}".format(selected1, selected2))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Choose Your Book"))
        self.label_2.setText(_translate("Form", "Choose Your Payment Method"))
        self.label_3.setText(_translate("Form", "Text"))
        self.radioButton_py.setText(_translate("Form", "Python"))
        self.radioButton_java.setText(_translate("Form", "Java"))
        self.radioButton_javascript.setText(_translate("Form", "JavaScript"))
        self.radioButton_debit.setText(_translate("Form", "Debit/Credit Card"))
        self.radioButton_paypal.setText(_translate("Form", "Paypal"))
        self.radioButton_cash.setText(_translate("Form", "Cash"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
